// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmpslawwsepsitqxmqzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtcHNsYXd3c2Vwc2l0cXhtcXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMTc0MTAsImV4cCI6MjA4NjU5MzQxMH0.DCnSIXDH-abE5-MrSqE_lpJIasxDNdU_7LinIY_RdDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);